default_stages:
  - commit

repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.12
        args:
          - -l 120
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.0
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        entry: mypy .
        additional_dependencies: [ types-requests==2.32.0.20241016 ]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-docstring-first
        stages:
          - commit
          - push
      - id: check-merge-conflict
        stages:
          - push
      - id: flake8
        stages:
          - commit
          - push
        args:
          - --max-line-length=120
          - --ignore=E203,W503,E704
      - id: trailing-whitespace
        stages:
          - commit
          - push
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.svg$
